### ISSUE TITLE
shiro-redis-session jar包是要自己编译吗？

### ISSUE THREAD

**Issue by zhoujie-cn** [xiaolongyuan/shiro-redis-session#4]

**Comment by xiaolongyuan** [comment]
是的

**Comment by zhoujie-cn** [comment]
打包成什么形式的jar包？ 可运行jar包(执行jar文件).          
还是普通的jar包

**Comment by xiaolongyuan** [comment]
普通 jar

**Comment by zhoujie-cn** [comment]
我将shiro-redis-session打包成jar后，在从shiro-redis-session-web中将打包成的jar放到web lib中去， 但是报了一个我一下午都无法解决的问题，
首先shiro-redis-session-web里面的jar包已经全部到了项目发布路径里面,redis我也已经开启了。  附件是生成的jar 和错误文件。 您有空能看一下是不是生成的jar有什么问题吗？


  ‍

------------------ 原始邮件 ------------------
发件人: "longyuan";<notifications@github.com>;
发送时间: 2017年4月17日(星期一) 下午2:15
收件人: "xiaolongyuan/shiro-redis-session"<shiro-redis-session@noreply.github.com>; 
抄送: "zh_coder"<631463730@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xiaolongyuan/shiro-redis-session] shiro-redis-session jar包是要自己编译吗？ (#4)
